# questions for feedback_course
f_c = [
    ['grading_policy','Grading policy',
     'Very Strict (too few will get an A!)', 'Seems fair',
     'Seems Random', 'Too lousy (everyone would get an A!)',
     'Unclear'],
    ['quality_of_tests', 'Quality of tests ',
     'Too challenging (unsolvable)',
     'Challenging (good paper)', 'OK, much from lectures',
     'Mundane (plug and chug)'],
    ['challenging', 'Was the course challenging?',
     'Too callenging and demanding', 'Fairly challenging',
     'Easy (much was already known)', 'Too easy (no learning)'] ,
    ['appreciation', 'Were the students able to appreciate subject?',
     'Yes understood the importance of subject in real life',
     'Somewhat useful subject',
     'Can do without it', 'Pretty useless'],
    ['relevance', 'Relevance of tests and material taught',
     'Totally relevant', 'Irrelevant much on tests was not taught'],
    ['availibility_material', 'Availability of prescribed material',
     'Easily available in library and online',
     'Available after a lot of work',
     'Archaic links did not worked'],
]

f_i = [
    ['teaching_method', 'Teaching method',
     'Powerpoint-Presentation Preffered',
     'Powerpoint-Presentation Not-Preffered', 'Chalk and Board'],
    ['evaluation_time', 'Evaluation time', '< 1 week', '< 2 week',
     '< 3 week' ,'> 4 week'],
    ['regularity', 'Regularity of instructor', 'No class missed',
    'Seldom Misses', 'Frequent Misses'],
    ['legibility',
     'Legibility on board', 'Printed', 'Legible With efforts',
     'Illegible/too small'],
    ['audibility', 'Audibility', 'Clear', 'Audible With efforts',
     'Almost incomprehensible'],
    ['ability_to_explain', 'Ability to explain',
     'Able to explain all difficult things',
     'Able to explain simple things',
     'Unable to explain/ doesn\'t intend to explain'],
    ['willingness_outside_class',
     'Willingness to help outside class',
     'Very accessible and willing', 'Rarely meets outside'],
    ['interactiveness', 'Interactiveness in class',
     'Too much interaction/ no real teaching',
     'Workshop like', 'Perfect level of interaction', 'No interaction'],
    ['length_lecture', 'Length of lecture', 'Too short',
     'Perfect', 'Long', 'Too long'],
]

f_l = [
    ['quality_assignment', 'Quality of lab tasks',
     'Too challenging (unsolvable tasks)',
     'Challenging (good tasks)', 'OK, much from board',
     'Mechanical (plug and chug)'],
    ['assessment', 'Assessment of practical/tutorial',
     'Very Strict (few will get an A!)', 'Seems quite fair',
     'Seems pretty Random', 'Too lousy (most would get an A!)',
     'Not Clear'],
    ['regularity', 'Regularity of TA', 'No lab missed',
     'Seldom misses', 'Frequent misses'],
    ['helpfullness_ta', 'Helpfulness of TA',
     'Super helpful and knowledgable',
     'Somewhat helpful atleast conducive',
     'Didn\'t atleast hamper study',
     'Useless, a hinderance'], 
    ['length', 'Length of lab', 'Very short',
     'Perfect length', 'Long but manageable', 'Unnecessarily long'],
    ['usefullness', 'Usefulness of Lab', 'Great (couldn\'t do without)',
     'Good (did help)', 'OK (could do without)',
     'Useless (waste of time)'],
]

f_t = [
    ['quality_assignment', 'Quality of assignment',
     'Too challenging (unsolvable assignments)',
     'Challenging (good assignements)', 'OK, much from the tutorial',
     'Mundane (plug-chug)'],
    ['assessment', 'Assessment of practical/tutorial',
     'Very Strict (no will get an A!)', 'Seems justified',
     'Seems random', 'Too lousy (all would get an A!)',
     'No clarity on this'],
    ['regularity', 'Regularity of TA', 'No tutorial missed',
     'Few tutorials missed', 'Many tutorials missed'],
    ['helpfullness_ta', 'Helpfulness of TA',
     'Very helpful and knowledgable',
     'Somewhat helpful, but is atleast conducive',
     'Not much helpful, doesn\'t hamper study though',
     'Useless, actually hinderance'], 
    ['length', 'Length of class', 'Quite short',
     'Perfectly fine', 'Long but OK', 'Very long'],
    ['usefullness', 'Usefulness of Lab', 'Great (could not do without)',
     'Good (somewhat usefull)', 'OK (but could do without it)',
     'Useless (total waste of time)'],
]
